version: 2
updates:
  - package-ecosystem: "npm"
    target-branch: "main"
    directory: "/src"
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"
    labels:
      - "frontend"
      - "dependencies"
    reviewers:
      - "itskovacs"
    groups:
      frontend-angular-dependencies:
        patterns:
          - "@angular*"
      frontend-primeng-dependencies:
        patterns:
          - "@primeng*"
          - "primeng"
          - "primeicons"
      frontend-twcss-dependencies:
        patterns:
          - "tailwind*"
      frontend-charts-dependencies:
        patterns:
          - "*chart*"
      frontend-misc-dependencies:
        patterns:
          - "@material-symbols*"